### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by EndreEndi** [ondraczsk/TajnaMysickaVec#2]
Update the plugin?

**Comment by EndreEndi** [comment]
Fix crash in tessteract

**Comment by ondraczsk** [comment]
try to fix it, i cant fixing plugins :dagger: 

make pull request, or contact  @majovec

**Comment by majovec** [comment]
Plugin is 100% function and fix crash ? contact bitch @CreeperFace01

**Comment by ondraczsk** [comment]
yes :D

**Comment by ondraczsk** [comment]
@majovec is our hacker xD

**Comment by majovec** [comment]
@ondraczsk  no i biznisman
